services:
  - type: web
    name: auction-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: CLIENT_URL
        value: https://live-online-auction-platform.vercel.app
